### ISSUE TITLE
Incompatible with sharp module

### ISSUE THREAD

**Issue by jvolker** [jstransformers/jstransformer-nunjucks#41]
This module seems incompatible with `sharp`. 

Using Node 12.16.3 installing `npm install jstransformer-nunjucks` (1.0.0) and then 

`npm install sharp`

returns this:

```
> fsevents@2.1.3 install /Users/js/Downloads/test-sharp/node_modules/fsevents
> node-gyp rebuild

gyp: binding.gyp not found (cwd: /Users/js/Downloads/test-sharp/node_modules/fsevents) while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/js/Downloads/test-sharp/node_modules/fsevents
gyp ERR! node -v v12.16.3
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 

> sharp@0.25.2 install /Users/js/Downloads/test-sharp/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install --runtime=napi) || (node-gyp rebuild && node install/dll-copy)

info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.9.1/libvips-8.9.1-darwin-x64.tar.gz
```

Without `jstransformer-nunjucks` this problem doesn't exist. Is there anything I should do differently?

Thanks.

**Comment by jvolker** [comment]
This was actually a problem with an old NPM version.
